<?xml version="1.0" standalone="yes"?>

<?program_dtd version="1"?>

<!DOCTYPE PROGRAM [

<!ELEMENT PROGRAM (DESCRIPTION?,
                   INFO_SOURCE?,
                   PROCESSOR?,
                   COMPILER?,
                   DATATYPES?,
                   MEMORY_MAP?,
                   REGISTER_VALUES?,
                   CODE?,
                   DATA?,
                   EQUATES?,
                   COMMENTS?,
                   PROPERTIES?,
                   BOOKMARKS?,
                   PROGRAM_TREES?,
                   PROGRAM_ENTRY_POINTS?,
                   RELOCATION_TABLE?,
                   SYMBOL_TABLE?,
                   FUNCTIONS?,
                   MARKUP?,
                   EXT_LIBRARY_TABLE?)>
  <!ATTLIST PROGRAM NAME       CDATA #REQUIRED>
  <!ATTLIST PROGRAM EXE_PATH   CDATA #IMPLIED>
  <!ATTLIST PROGRAM EXE_FORMAT CDATA #IMPLIED>
  <!ATTLIST PROGRAM IMAGE_BASE CDATA #IMPLIED>

<!ELEMENT DISPLAY_SETTINGS EMPTY>
  <!ATTLIST DISPLAY_SETTINGS FORMAT           (hex | decimal | octal | binary | char) #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS SIGNED           (y | n)                                 #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS ZERO_PAD         (y | n)                                 #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS ENDIAN           (big | little)                          #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS SHOW_TERMINATOR  (y | n)                                 #IMPLIED>

<!ELEMENT DESCRIPTION    (#PCDATA)>
<!ELEMENT REGULAR_CMT    (#PCDATA)>
<!ELEMENT REPEATABLE_CMT (#PCDATA)>
<!ELEMENT TYPEINFO_CMT   (#PCDATA)>

<!ELEMENT INFO_SOURCE EMPTY>
  <!ATTLIST INFO_SOURCE USER      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE TOOL      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE FILE      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE TIMESTAMP CDATA #IMPLIED>

<!ELEMENT PROCESSOR EMPTY>
  <!ATTLIST PROCESSOR NAME              CDATA          #REQUIRED>
  <!ATTLIST PROCESSOR FAMILY            CDATA          #IMPLIED>
  <!ATTLIST PROCESSOR LANGUAGE_PROVIDER CDATA          #IMPLIED>
  <!ATTLIST PROCESSOR ENDIAN            (big | little) #IMPLIED>
  <!ATTLIST PROCESSOR ADDRESS_MODEL     CDATA          #IMPLIED>

<!-- TODO: expand compiler tag -->
<!ELEMENT COMPILER EMPTY>
  <!ATTLIST COMPILER NAME CDATA #REQUIRED>

<!ELEMENT MEMORY_MAP (MEMORY_SECTION*)>

<!ELEMENT MEMORY_SECTION ((MEMORY_CONTENTS*) | (BIT_MAPPED?))>
  <!ATTLIST MEMORY_SECTION NAME         CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION START_ADDR   CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION LENGTH       CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION PERMISSIONS  (r | w | x | rw | rx | wx | rwx)  #IMPLIED>
  <!ATTLIST MEMORY_SECTION VOLATILE     (y | n)                           #IMPLIED>
  <!ATTLIST MEMORY_SECTION COMMENT      CDATA                             #IMPLIED>

<!ELEMENT MEMORY_CONTENTS EMPTY>
  <!ATTLIST MEMORY_CONTENTS START_ADDR   CDATA  #IMPLIED>
  <!ATTLIST MEMORY_CONTENTS FILE_NAME    CDATA  #REQUIRED>
  <!ATTLIST MEMORY_CONTENTS FILE_OFFSET  CDATA  #REQUIRED>
  <!ATTLIST MEMORY_CONTENTS LENGTH       CDATA  #IMPLIED>

<!ELEMENT BIT_MAPPED EMPTY>
  <!ATTLIST BIT_MAPPED SOURCE_ADDRESS  CDATA  #REQUIRED>

<!ELEMENT REGISTER_VALUES (REGISTER_VALUE_RANGE*)>

<!ELEMENT REGISTER_VALUE_RANGE EMPTY>
  <!ATTLIST REGISTER_VALUE_RANGE REGISTER      CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE VALUE         CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE START_ADDRESS CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE LENGTH        CDATA #REQUIRED>

<!ELEMENT CODE (CODE_BLOCK*)>

<!ELEMENT CODE_BLOCK EMPTY>
  <!ATTLIST CODE_BLOCK  START  CDATA  #REQUIRED>
  <!ATTLIST CODE_BLOCK  END    CDATA  #REQUIRED>

<!ELEMENT DATA (DEFINED_DATA*)>

<!ELEMENT DEFINED_DATA (TYPEINFO_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST DEFINED_DATA ADDRESS             CDATA  #REQUIRED>
  <!ATTLIST DEFINED_DATA DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST DEFINED_DATA DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST DEFINED_DATA SIZE                CDATA  #IMPLIED>

<!ELEMENT EQUATES (EQUATE_GROUP*)>

<!ELEMENT EQUATE_GROUP (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?, (EQUATE | BIT_MASK)*)>
  <!ATTLIST EQUATE_GROUP NAME       CDATA       #IMPLIED>
  <!ATTLIST EQUATE_GROUP BIT_FIELD  (yes | no)  #IMPLIED>

<!ELEMENT EQUATE (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST EQUATE NAME     CDATA  #REQUIRED>
  <!ATTLIST EQUATE VALUE    CDATA  #REQUIRED>
  <!ATTLIST EQUATE BIT_MASK CDATA  #IMPLIED>

<!ELEMENT BIT_MASK (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST BIT_MASK NAME   CDATA  #REQUIRED>
  <!ATTLIST BIT_MASK VALUE  CDATA  #REQUIRED>

<!ELEMENT COMMENTS (COMMENT*)>

<!ELEMENT COMMENT (#PCDATA)>
  <!ATTLIST COMMENT ADDRESS  CDATA                                            #REQUIRED>
  <!ATTLIST COMMENT TYPE     (end-of-line | repeatable | pre | post | plate)  #REQUIRED>

<!ELEMENT PROPERTIES (PROPERTY*)>

<!ELEMENT PROPERTY EMPTY>
  <!ATTLIST PROPERTY NAME     CDATA                                                #REQUIRED>
  <!ATTLIST PROPERTY ADDRESS  CDATA                                                #IMPLIED>
  <!ATTLIST PROPERTY TYPE     (string | long | int | double | void | bool | date)  #IMPLIED>
  <!ATTLIST PROPERTY VALUE    CDATA                                                #IMPLIED>

<!ELEMENT BOOKMARKS (BOOKMARK*)>

<!ELEMENT BOOKMARK EMPTY>
  <!ATTLIST BOOKMARK ADDRESS     CDATA  #REQUIRED>
  <!ATTLIST BOOKMARK TYPE        CDATA  #IMPLIED>
  <!ATTLIST BOOKMARK CATEGORY    CDATA  #IMPLIED>
  <!ATTLIST BOOKMARK DESCRIPTION CDATA  #IMPLIED>

<!ELEMENT PROGRAM_TREES (TREE*)>

<!ELEMENT TREE ((FOLDER | FRAGMENT)*)>
  <!ATTLIST TREE NAME CDATA #REQUIRED>

<!ELEMENT FOLDER ((FOLDER | FRAGMENT)*)>
  <!ATTLIST FOLDER NAME CDATA #REQUIRED>

<!ELEMENT FRAGMENT (ADDRESS_RANGE)*>
  <!ATTLIST FRAGMENT NAME CDATA #REQUIRED>

<!ELEMENT ADDRESS_RANGE EMPTY>
  <!ATTLIST ADDRESS_RANGE START  CDATA  #REQUIRED>
  <!ATTLIST ADDRESS_RANGE END    CDATA  #REQUIRED>

<!ELEMENT PROGRAM_ENTRY_POINTS (PROGRAM_ENTRY_POINT*)>

<!ELEMENT PROGRAM_ENTRY_POINT EMPTY>
  <!ATTLIST PROGRAM_ENTRY_POINT  ADDRESS  CDATA  #REQUIRED>

<!ELEMENT RELOCATION_TABLE (RELOCATION*)>

<!ELEMENT RELOCATION EMPTY>
  <!ATTLIST RELOCATION ADDRESS  CDATA  #REQUIRED>
  <!ATTLIST RELOCATION TYPE     CDATA  #REQUIRED>
  <!ATTLIST RELOCATION VALUE    CDATA  #REQUIRED>
  <!ATTLIST RELOCATION BYTES    CDATA  #IMPLIED>

<!ELEMENT SYMBOL_TABLE (SYMBOL*)>

<!ELEMENT SYMBOL EMPTY>
  <!ATTLIST SYMBOL ADDRESS   		CDATA            					 #REQUIRED>
  <!ATTLIST SYMBOL NAME      		CDATA             					 #REQUIRED>
  <!ATTLIST SYMBOL NAMESPACE 		CDATA             					 #IMPLIED>
  <!ATTLIST SYMBOL TYPE      		(global | local)  					 #IMPLIED>
  <!ATTLIST SYMBOL SOURCE_TYPE      (USER_DEFINED | IMPORTED | ANALYSIS) #IMPLIED>
  <!ATTLIST SYMBOL PRIMARY   		(y | n)           					 #IMPLIED>
  <!ATTLIST SYMBOL MANGLED   		CDATA             					 #IMPLIED>

<!ELEMENT FUNCTIONS (FUNCTION*)>

<!ELEMENT FUNCTION (RETURN_TYPE?, ADDRESS_RANGE*, REGULAR_CMT?, REPEATABLE_CMT?, TYPEINFO_CMT?, STACK_FRAME?, REGISTER_VAR*)>
  <!ATTLIST FUNCTION ENTRY_POINT       CDATA   #REQUIRED>
  <!ATTLIST FUNCTION NAME              CDATA   #IMPLIED>
  <!-- TODO: create xml attrs for each known attribute type -->
  <!ATTLIST FUNCTION LIBRARY_FUNCTION  (y | n) #IMPLIED>

<!ELEMENT RETURN_TYPE EMPTY>
  <!ATTLIST RETURN_TYPE DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST RETURN_TYPE DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST RETURN_TYPE SIZE                CDATA  #IMPLIED>

<!ELEMENT STACK_FRAME (STACK_VAR*)>
  <!ATTLIST STACK_FRAME LOCAL_VAR_SIZE         CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME PARAM_OFFSET           CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME REGISTER_SAVE_SIZE     CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME RETURN_ADDR_SIZE       CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME BYTES_PURGED           CDATA    #IMPLIED>

<!ELEMENT STACK_VAR (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST STACK_VAR STACK_PTR_OFFSET    CDATA  #REQUIRED> <!-- offset from the stack ptr value at function entry -->
  <!ATTLIST STACK_VAR FRAME_PTR_OFFSET    CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR NAME                CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST STACK_VAR DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR SIZE                CDATA  #IMPLIED>

<!ELEMENT REGISTER_VAR (REGULAR_CMT?)>
  <!ATTLIST REGISTER_VAR NAME                CDATA  #REQUIRED>
  <!ATTLIST REGISTER_VAR REGISTER            CDATA  #REQUIRED>
  <!ATTLIST REGISTER_VAR DATATYPE            CDATA  #IMPLIED>
  <!ATTLIST REGISTER_VAR DATATYPE_NAMESPACE  CDATA  #IMPLIED>

<!ELEMENT MARKUP (MEMORY_REFERENCE      |
                  STACK_REFERENCE       |
                  EXT_LIBRARY_REFERENCE |
                  EQUATE_REFERENCE      |
                  MANUAL_OPERAND        |
                  MANUAL_INSTRUCTION)*>

<!-- An OPERAND_INDEX is omitted for a mnemonic reference    -->
<!-- The first operand is identified with OPERAND_INDEX=0 -->
<!ELEMENT MEMORY_REFERENCE EMPTY>
  <!ATTLIST MEMORY_REFERENCE ADDRESS        CDATA    #REQUIRED>
  <!ATTLIST MEMORY_REFERENCE OPERAND_INDEX  CDATA    #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE USER_DEFINED   (y | n)  #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE TO_ADDRESS     CDATA    #REQUIRED>
  <!ATTLIST MEMORY_REFERENCE BASE_ADDRESS   CDATA    #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE PRIMARY        (y | n)  #IMPLIED>

<!ELEMENT STACK_REFERENCE EMPTY>
  <!ATTLIST STACK_REFERENCE ADDRESS          CDATA    #REQUIRED>
  <!ATTLIST STACK_REFERENCE OPERAND_INDEX    CDATA    #IMPLIED>
  <!ATTLIST STACK_REFERENCE USER_DEFINED     (y | n)  #IMPLIED>
  <!ATTLIST STACK_REFERENCE STACK_PTR_OFFSET CDATA    #REQUIRED> <!-- offset from the stack ptr value at function entry -->
  <!ATTLIST STACK_REFERENCE FRAME_PTR_OFFSET CDATA    #IMPLIED>

<!ELEMENT EXT_LIBRARY_REFERENCE EMPTY>
  <!ATTLIST EXT_LIBRARY_REFERENCE ADDRESS        CDATA    #REQUIRED>
  <!ATTLIST EXT_LIBRARY_REFERENCE OPERAND_INDEX  CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE USER_DEFINED   (y | n)  #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_PROG_NAME  CDATA    #REQUIRED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_LABEL      CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_ORDINAL    CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_ADDR       CDATA    #IMPLIED>

<!ELEMENT EQUATE_REFERENCE EMPTY>
  <!ATTLIST EQUATE_REFERENCE ADDRESS        CDATA  #REQUIRED>
  <!ATTLIST EQUATE_REFERENCE OPERAND_INDEX  CDATA  #IMPLIED>
  <!ATTLIST EQUATE_REFERENCE NAME           CDATA  #REQUIRED>
  <!ATTLIST EQUATE_REFERENCE VALUE          CDATA  #IMPLIED>

<!ELEMENT MANUAL_OPERAND (#PCDATA)>
  <!ATTLIST MANUAL_OPERAND ADDRESS        CDATA  #REQUIRED>
  <!ATTLIST MANUAL_OPERAND OPERAND_INDEX  CDATA  #REQUIRED>

<!ELEMENT MANUAL_INSTRUCTION (#PCDATA)>
  <!ATTLIST MANUAL_INSTRUCTION ADDRESS CDATA #REQUIRED>

<!ELEMENT EXT_LIBRARY_TABLE (EXT_LIBRARY*)>

<!ELEMENT EXT_LIBRARY EMPTY>
  <!ATTLIST EXT_LIBRARY NAME  CDATA  #REQUIRED>
  <!ATTLIST EXT_LIBRARY PATH  CDATA  #IMPLIED>

<!-- ************************************************************* -->
<!--                                                               -->
<!--                Data DTD                                       -->
<!--                                                               -->
<!-- ************************************************************* -->

<!ELEMENT DATATYPES (STRUCTURE | UNION | FUNCTION_DEF | ENUM | TYPE_DEF)*>

<!ELEMENT MEMBER (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST MEMBER OFFSET              CDATA  #REQUIRED>
  <!ATTLIST MEMBER DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST MEMBER DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST MEMBER NAME                CDATA  #IMPLIED>
  <!ATTLIST MEMBER SIZE                CDATA  #IMPLIED>

<!ELEMENT STRUCTURE (REGULAR_CMT?, REPEATABLE_CMT?, MEMBER*)>
  <!ATTLIST STRUCTURE NAME             CDATA   #REQUIRED>
  <!ATTLIST STRUCTURE NAMESPACE        CDATA   #IMPLIED>
  <!ATTLIST STRUCTURE SIZE             CDATA   #IMPLIED>
  <!ATTLIST STRUCTURE VARIABLE_LENGTH  (y | n) #IMPLIED>

<!ELEMENT UNION (REGULAR_CMT?, REPEATABLE_CMT?, MEMBER*)>
  <!ATTLIST UNION NAME       CDATA  #REQUIRED>
  <!ATTLIST UNION NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST UNION SIZE       CDATA  #IMPLIED>

<!ELEMENT FUNCTION_DEF (REGULAR_CMT?, REPEATABLE_CMT?, RETURN_TYPE?, PARAMETER*)>
  <!ATTLIST FUNCTION_DEF NAME       CDATA  #REQUIRED>
  <!ATTLIST FUNCTION_DEF NAMESPACE  CDATA  #IMPLIED>

<!ELEMENT PARAMETER (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST PARAMETER ORDINAL             CDATA  #REQUIRED>
  <!ATTLIST PARAMETER DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST PARAMETER DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST PARAMETER NAME                CDATA  #IMPLIED>
  <!ATTLIST PARAMETER SIZE                CDATA  #IMPLIED>

<!ELEMENT TYPE_DEF (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST TYPE_DEF NAME                CDATA #REQUIRED>
  <!ATTLIST TYPE_DEF NAMESPACE           CDATA #IMPLIED>
  <!ATTLIST TYPE_DEF DATATYPE            CDATA #REQUIRED>
  <!ATTLIST TYPE_DEF DATATYPE_NAMESPACE  CDATA #IMPLIED>

<!ELEMENT ENUM (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?, ENUM_ENTRY*)>
  <!ATTLIST ENUM NAME       CDATA  #REQUIRED>
  <!ATTLIST ENUM NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST ENUM SIZE       CDATA  #IMPLIED>

<!ELEMENT ENUM_ENTRY (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST ENUM_ENTRY NAME   CDATA  #REQUIRED>
  <!ATTLIST ENUM_ENTRY VALUE  CDATA  #REQUIRED>

]>
<PROGRAM NAME="Armored Unit.ws" EXE_PATH="/Armored Unit.ws" EXE_FORMAT="Raw Binary" IMAGE_BASE="0000:0000">
    <INFO_SOURCE USER="up-n-atom" TOOL="Ghidra 9.2.2" TIMESTAMP="Tue Mar 09 13:13:45 EST 2021" />
    <PROCESSOR NAME="x86" LANGUAGE_PROVIDER="x86:LE:16:Real Mode:default" ENDIAN="little" />
    <DATATYPES />
    <MEMORY_MAP>
        <MEMORY_SECTION NAME="DATA" START_ADDR="1000:0000" LENGTH="0x886" PERMISSIONS="rw" />
        <MEMORY_SECTION NAME="BSS" START_ADDR="1000:0886" LENGTH="0x78c" PERMISSIONS="rw" />
        <MEMORY_SECTION NAME="XSTACK" START_ADDR="1000:1020" LENGTH="0xa00" PERMISSIONS="rw" />
        <MEMORY_SECTION NAME="SAVE_DATA" START_ADDR="1000:1e00" LENGTH="0x200" PERMISSIONS="rw" />
        <MEMORY_SECTION NAME="TEXT" START_ADDR="8000:0000" LENGTH="0xaf" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x0" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="SWANMAIN_TEXT" START_ADDR="8000:00af" LENGTH="0x484" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0xaf" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="SPRINTF_TEXT" START_ADDR="8000:0533" LENGTH="0x984" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x533" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="SYSTEM_TEXT" START_ADDR="8000:0eb7" LENGTH="0x499" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0xeb7" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="PAD_TEXT" START_ADDR="8000:1350" LENGTH="0x185" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x1350" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="MEMORY_TEXT" START_ADDR="8000:14d5" LENGTH="0xc56" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x14d5" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="select_TEXT" START_ADDR="8000:212b" LENGTH="0x9f3" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x212b" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="ASM_TEXT" START_ADDR="8000:2b1e" LENGTH="0x8e" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x2b1e" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="SERIAL_TEXT" START_ADDR="8000:2bac" LENGTH="0x546" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x2bac" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="IP_MES_TEXT" START_ADDR="8000:30f2" LENGTH="0x761" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x30f2" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="DEBUG_TEXT" START_ADDR="8000:3853" LENGTH="0x16c" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x3853" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="CONSOLE_TEXT" START_ADDR="8000:39bf" LENGTH="0x32b" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x39bf" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="TITLE_TEXT" START_ADDR="8000:3cea" LENGTH="0x58c" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x3cea" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="LOGO_TEXT" START_ADDR="8000:4276" LENGTH="0xd8" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x4276" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="m_game_TEXT" START_ADDR="8000:434e" LENGTH="0x24f7" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x434e" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="m_sub_TEXT" START_ADDR="8000:6845" LENGTH="0x1e67" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x6845" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="m_weapon_TEXT" START_ADDR="8000:86ac" LENGTH="0x9c6" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x86ac" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="m_cpu2p_TEXT" START_ADDR="8000:9072" LENGTH="0xa93" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x9072" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="menu_TEXT" START_ADDR="8000:9b05" LENGTH="0x1ae7" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x9b05" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="unisel_TEXT" START_ADDR="8000:b5ec" LENGTH="0x19e7" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0xb5ec" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="stagesel_TEXT" START_ADDR="8000:cfd3" LENGTH="0xa95" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0xcfd3" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="tuneup_TEXT" START_ADDR="8000:da68" LENGTH="0x1f97" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0xda68" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="story_TEXT" START_ADDR="8000:f9ff" LENGTH="0xa22" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0xf9ff" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="PUT_TEXT_TEXT" START_ADDR="9000:0421" LENGTH="0x5a7" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x10421" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="SOUND_CODE" START_ADDR="9000:09d0" LENGTH="0x5f7" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x109c8" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="ending_TEXT" START_ADDR="9000:0fc7" LENGTH="0x76e" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x10fbf" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="flash_TEXT" START_ADDR="9000:1735" LENGTH="0x1b5" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x1172d" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="_GENETEXT" START_ADDR="9000:18ea" LENGTH="0x43d" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x118e2" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="SWAN_L_C_TEXT" START_ADDR="9000:1d27" LENGTH="0x3f7" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x11d1f" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="_KNOTEXT" START_ADDR="9000:211e" LENGTH="0x10" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x12116" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="STRING_TEXT" START_ADDR="9000:212e" LENGTH="0xf" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x12126" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="GENERAL_TEXT" START_ADDR="9000:213d" LENGTH="0x7" PERMISSIONS="rx">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x12135" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="_GHOST_DATA" START_ADDR="9000:f000" LENGTH="0x886" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x1213c" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="FAR_DATA" START_ADDR="a000:0000" LENGTH="0x6c0" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x129c2" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="SPRINTF_1_DATA" START_ADDR="a000:06c0" LENGTH="0x11" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x13082" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="SPRINTF_2_DATA" START_ADDR="a000:06d2" LENGTH="0x11" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x13093" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="SPRINTF_3_DATA" START_ADDR="a000:06e4" LENGTH="0x18" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x130a4" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="SPRINTF_4_DATA" START_ADDR="a000:06fc" LENGTH="0x14" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x130bc" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="SPRINTF_5_DATA" START_ADDR="a000:0710" LENGTH="0x40" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x130d0" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="MEMORY_1_DATA" START_ADDR="a000:0750" LENGTH="0x14" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x13110" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="MEMORY_2_DATA" START_ADDR="a000:0764" LENGTH="0x1b" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x13124" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="MEMORY_3_DATA" START_ADDR="a000:0780" LENGTH="0x14" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x1313f" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="MEMORY_4_DATA" START_ADDR="a000:0794" LENGTH="0x12" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x13153" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="MEMORY_5_DATA" START_ADDR="a000:07a6" LENGTH="0x15" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x13165" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="MEMORY_6_DATA" START_ADDR="a000:07bc" LENGTH="0x15" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x1317a" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="MEMORY_7_DATA" START_ADDR="a000:07d2" LENGTH="0x18" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x1318f" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="MEMORY_8_DATA" START_ADDR="a000:07ea" LENGTH="0xc" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x131a7" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="select_1_DATA" START_ADDR="a000:07f6" LENGTH="0x1d" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x131b3" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="select_2_DATA" START_ADDR="a000:0814" LENGTH="0x1d" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x131d0" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="select_3_DATA" START_ADDR="a000:0832" LENGTH="0x1d" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x131ed" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="select_4_DATA" START_ADDR="a000:0850" LENGTH="0x1d" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x1320a" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="select_5_DATA" START_ADDR="a000:086e" LENGTH="0x1d" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x13227" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="select_6_DATA" START_ADDR="a000:088c" LENGTH="0x1d" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x13244" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="select_7_DATA" START_ADDR="a000:08aa" LENGTH="0x1d" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x13261" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="select_8_DATA" START_ADDR="a000:08c8" LENGTH="0x1d" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x1327e" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="select_9_DATA" START_ADDR="a000:08e6" LENGTH="0x1d" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x1329b" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="select_10_DATA" START_ADDR="a000:0904" LENGTH="0x1d" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x132b8" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="select_11_DATA" START_ADDR="a000:0922" LENGTH="0x1d" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x132d5" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="select_12_DATA" START_ADDR="a000:0940" LENGTH="0x1d" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x132f2" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="select_13_DATA" START_ADDR="a000:095e" LENGTH="0x1d" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x1330f" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="select_14_DATA" START_ADDR="a000:097c" LENGTH="0x1d" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x1332c" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="select_15_DATA" START_ADDR="a000:099a" LENGTH="0x1d" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x13349" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="select_16_DATA" START_ADDR="a000:09b8" LENGTH="0x1d" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x13366" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="select_17_DATA" START_ADDR="a000:09d6" LENGTH="0x1d" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x13383" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="select_18_DATA" START_ADDR="a000:09f4" LENGTH="0x1d" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x133a0" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="select_19_DATA" START_ADDR="a000:0a12" LENGTH="0x48" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x133bd" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="select_20_DATA" START_ADDR="a000:0a5a" LENGTH="0xa" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x13405" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="select_21_DATA" START_ADDR="a000:0a64" LENGTH="0xa" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x1340f" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="select_22_DATA" START_ADDR="a000:0a6e" LENGTH="0xa" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x13419" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="select_23_DATA" START_ADDR="a000:0a78" LENGTH="0xa" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x13423" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="select_24_DATA" START_ADDR="a000:0a82" LENGTH="0x10" PERMISSIONS="r">
            <MEMORY_CONTENTS FILE_NAME="Armored Unit.ws.bytes" FILE_OFFSET="0x1342d" />
        </MEMORY_SECTION>